### ISSUE TITLE
Cannot find module 'cross-spawn'

### ISSUE THREAD

**Issue by codingChewie** [kimlimjustin/is-hidden-file#1]
Found this NPM package after reading: "[How to ignore hidden files in fs.readdir result](https://stackoverflow.com/questions/18973655/how-to-ingnore-hidden-files-in-fs-readdir-result)" but upon install attempt:

```bash
npm i is-hidden-file
```

per [Installation docs](https://github.com/kimlimjustin/is-hidden-file#installation) but throws the error:

```bash
Error: Cannot find module 'cross-spawn'
Require stack:
- /Users/path/to/project/node_modules/is-hidden-file/src/install.js
```

OS: Mac Mojave
Node: v14.17.1
NPM: 6.14.13

[`cross-spawn`](https://www.npmjs.com/package/cross-spawn) is missing as a dependency in _package.json_.

**Comment by kimlimjustin** [comment]
thanks for your report, I'll take a look into it soon.

**Comment by kimlimjustin** [comment]
I've committed a fix for this, could you please try the latest commit (9e08bec617a38c8b6b763beb2b6c70368869df9d)?

**Comment by codingChewie** [comment]
Tested within my project with `npm link is-hidden-file` and:

```
const { isHiddenFile } = require('is-hidden-file')
console.log(isHiddenFile('.git'))
console.log(isHiddenFile('README.md'))
```

results logged to console successfully, issue of missing dependency resolved.

**Comment by kimlimjustin** [comment]
Thanks for confirming it!
